import { analyzeReceiptOcr } from '../receipt-ocr-pipeline.js';
import { getAccessToken } from '../auth-gate.js';
import { recognizeImage } from './documentRecognition.js';
import { prepareReceiptImageForVision } from './receiptVisionImage.js';
import { getAiWorkerUrl } from './expenseSuggestion.js';

export const RECEIPT_READER_PROVIDERS = Object.freeze(['tesseract', 'openai']);
export const DEFAULT_RECEIPT_READER_PROVIDER = 'tesseract';
export class ReceiptReaderError extends Error { constructor(code = 'RECEIPT_READER_UNAVAILABLE') { super('高精度読み取りに失敗しました。原本を確認して再試行してください。'); this.code = code; } }
const asText = (value, limit = 1000) => typeof value === 'string' && value.trim() ? value.trim().slice(0, limit) : null;
const asNumber = (value) => Number.isFinite(Number(value)) && Number(value) >= 0 ? Number(value) : null;
const round = (value) => Math.round((Number(value) || 0) * 100) / 100;

export function evaluateReceiptReaderQuality({ rawText = '', items = [], receiptTotalAmount = null, warnings = [] } = {}) {
  const asNumber = (value) => value == null ? null : Number.isFinite(Number(value)) && Number(value) >= 0 ? Number(value) : null;
  const source = Array.isArray(items) ? items : []; const valid = source.filter((item) => asText(item?.productName, 240) && asNumber(item?.amount) != null);
  const itemTotalAmount = round(valid.reduce((sum, item) => sum + Number(item.amount), 0)); const total = asNumber(receiptTotalAmount); const difference = total == null ? null : round(total - itemTotalAmount);
  const lowConfidenceCount = source.filter((item) => !asText(item?.productName, 240) || asNumber(item?.amount) == null || item?.needsReview).length;
  const status = !valid.length ? ((rawText || total != null || warnings.length) ? 'low_confidence' : 'failed') : total != null && Math.abs(difference) <= 1 && lowConfidenceCount === 0 ? 'success' : 'partial';
  return { status, candidateCount: valid.length, lowConfidenceCount, lineCount: String(rawText).split(/\r?\n/).filter(Boolean).length, monetaryLineCount: valid.length + (total == null ? 0 : 1), receiptTotalAmount: total, itemTotalAmount, difference, totalConsistent: total != null && Math.abs(difference) <= 1 };
}

export function normalizeReceiptReaderResult(value = {}) {
  const asNumber = (value) => value == null ? null : Number.isFinite(Number(value)) && Number(value) >= 0 ? Number(value) : null;
  const items = (Array.isArray(value.items) ? value.items : []).slice(0, 120).map((item) => ({ sourceText: asText(item?.sourceText), productName: asText(item?.productName, 240), quantity: asNumber(item?.quantity), unitPrice: asNumber(item?.unitPrice), amount: asNumber(item?.amount), confidence: Number.isFinite(Number(item?.confidence)) && Number(item.confidence) >= 0 && Number(item.confidence) <= 1 ? Number(item.confidence) : null, needsReview: Boolean(item?.needsReview) }));
  const result = { provider: RECEIPT_READER_PROVIDERS.includes(value.provider) ? value.provider : DEFAULT_RECEIPT_READER_PROVIDER, rawText: typeof value.rawText === 'string' ? value.rawText.slice(0, 16000) : '', vendor: asText(value.vendor, 240), purchaseDate: asText(value.purchaseDate, 20), receiptTotalAmount: asNumber(value.receiptTotalAmount), items, warnings: [...new Set((Array.isArray(value.warnings) ? value.warnings : []).map((warning) => asText(warning, 240)).filter(Boolean))].slice(0, 20), metadata: value.metadata && typeof value.metadata === 'object' ? value.metadata : {} };
  return { ...result, quality: evaluateReceiptReaderQuality(result) };
}

export const TesseractReceiptReader = Object.freeze({ provider: 'tesseract', async read({ file, onProgress = () => {}, recognize = recognizeImage } = {}) { const ocr = await recognize(file, onProgress); const analysis = analyzeReceiptOcr(ocr.rawText); return normalizeReceiptReaderResult({ provider: 'tesseract', rawText: ocr.rawText, vendor: analysis.headers.vendor, purchaseDate: analysis.headers.purchaseDate, receiptTotalAmount: analysis.headers.receiptTotalAmount, items: analysis.items.map((item) => ({ sourceText: item.sourceLines?.join('\n') || null, productName: item.productName, quantity: item.quantity, unitPrice: item.unitPrice, amount: item.amount, confidence: item.confidence, needsReview: item.confidence < .65 })), warnings: analysis.quality.status === 'low_confidence' ? ['商品明細の候補が不足しています。'] : [], metadata: { engine: ocr.engine, confidence: ocr.confidence, preprocessing: ocr.preprocessing } }); } });
async function asDataUrl(blob) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new ReceiptReaderError('IMAGE_READ_FAILED')); reader.onload = () => resolve(String(reader.result || '')); reader.readAsDataURL(blob); }); }
export const OpenAIReceiptReader = Object.freeze({ provider: 'openai', async read({ file, accessToken, workerUrl = getAiWorkerUrl(), fetchImpl = fetch, prepare = prepareReceiptImageForVision } = {}) { if (!workerUrl || !accessToken) throw new ReceiptReaderError('READER_CONFIGURATION_ERROR'); const prepared = await prepare(file); if (!prepared.input?.size || prepared.input.size > 4 * 1024 * 1024 || !['image/jpeg','image/png'].includes(prepared.input.type)) throw new ReceiptReaderError('IMAGE_TOO_LARGE'); let response; try { response = await fetchImpl(`${workerUrl.replace(/\/$/, '')}/read-receipt`, { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, 'content-type': 'application/json' }, body: JSON.stringify({ imageDataUrl: await asDataUrl(prepared.input), mimeType: prepared.input.type }) }); } catch { throw new ReceiptReaderError('READER_NETWORK_ERROR'); } let body; try { body = await response.json(); } catch { throw new ReceiptReaderError('READER_INVALID_RESPONSE'); } if (!response.ok) throw new ReceiptReaderError(body?.error?.code || 'READER_UNAVAILABLE'); return normalizeReceiptReaderResult({ ...body, provider: 'openai', metadata: { ...(body.metadata || {}), preprocessing: prepared.preprocessing } }); } });
export function configuredReceiptReaderProvider(value = globalThis.__APP_CONFIG__?.receiptReaderProvider) { return RECEIPT_READER_PROVIDERS.includes(value) ? value : DEFAULT_RECEIPT_READER_PROVIDER; }
export async function readReceipt(input = {}) { const provider = input.provider || configuredReceiptReaderProvider(); if (provider === 'tesseract') return TesseractReceiptReader.read(input); if (provider === 'openai') return OpenAIReceiptReader.read({ ...input, accessToken: input.accessToken || await getAccessToken() }); throw new ReceiptReaderError('READER_NOT_SUPPORTED'); }
export function compareReceiptReaderResults(tesseract, openai) { const summarize = (value) => { const result = normalizeReceiptReaderResult(value); return { rawText: result.rawText, vendor: result.vendor, purchaseDate: result.purchaseDate, receiptTotalAmount: result.receiptTotalAmount, itemCount: result.items.length, items: result.items.map(({ sourceText, productName, quantity, unitPrice, amount, needsReview }) => ({ sourceText, productName, quantity, unitPrice, amount, needsReview })), needsReviewCount: result.items.filter((item) => item.needsReview).length, itemTotalAmount: result.quality.itemTotalAmount, difference: result.quality.difference, processingMs: Number(result.metadata.processingMs) || null }; }; return { tesseract: summarize(tesseract), openai: summarize(openai), humanEvaluation: { correctNames: null, incorrectNames: null, correctAmounts: null, incorrectAmounts: null, missedItems: null, falseItems: null } }; }
export async function runReceiptReaderAbComparison(file, options = {}) { const tesseract = await TesseractReceiptReader.read({ file, recognize: options.recognize, onProgress: options.onTesseractProgress }); const openai = await OpenAIReceiptReader.read({ file, accessToken: options.accessToken || await getAccessToken(), workerUrl: options.workerUrl, fetchImpl: options.fetchImpl, prepare: options.prepare }); return { tesseract, openai, comparison: compareReceiptReaderResults(tesseract, openai) }; }
