import { createAuthService } from './services/auth.js';

const config = globalThis.__APP_CONFIG__ || {};
export const auth = createAuthService({ url: config.supabaseUrl, anonKey: config.supabaseAnonKey });
const $ = (selector) => document.querySelector(selector);

const authStyle = `<style>
  .auth-shell{min-height:100vh;box-sizing:border-box;display:grid;place-items:center;padding:clamp(16px,4vw,56px);background:#f4f7f8;color:#18313d;font-family:system-ui,"Yu Gothic UI","Hiragino Kaku Gothic ProN",sans-serif}
  .auth-layout{width:min(1080px,100%);display:grid;grid-template-columns:1.15fr .85fr;gap:clamp(20px,5vw,72px);align-items:stretch}
  .auth-intro{box-sizing:border-box;min-height:440px;padding:clamp(28px,5vw,60px);border-radius:14px;background:#123f55;color:#f7fbfc;box-shadow:0 10px 26px rgba(17,56,72,.1)}
  .auth-eyebrow{margin:0 0 13px;color:#b8dce4;font-size:12px;font-weight:800;letter-spacing:.1em}.auth-intro h1{max-width:520px;margin:0;font-size:clamp(28px,4vw,43px);line-height:1.24;letter-spacing:.03em}.auth-intro>p:last-of-type{max-width:520px;margin:18px 0 26px;line-height:1.8;color:#d9e8ec}.auth-points{display:grid;gap:12px;margin:0;padding:0;list-style:none}.auth-points li{padding-left:20px;position:relative;line-height:1.55}.auth-points li:before{content:"";position:absolute;left:0;top:.55em;width:8px;height:8px;border-radius:50%;background:#8dc7d2}
  .auth-card{box-sizing:border-box;align-self:center;padding:clamp(25px,4vw,40px);border:1px solid #dce5e8;border-radius:14px;background:#fff;box-shadow:0 7px 22px rgba(22,55,68,.07)}.auth-card .auth-eyebrow{color:#287084}.auth-card h1{margin:0 0 8px;color:#123f55;font-size:26px}.auth-card>p:not(.auth-eyebrow):not(.auth-error){margin:0 0 22px;color:#60717a;line-height:1.7;font-size:14px}.auth-card label,.auth-card input{display:block;width:100%;box-sizing:border-box}.auth-card label{margin:16px 0 6px;font-weight:750;font-size:14px;color:#284650}.auth-card input{min-height:46px;padding:10px 12px;border:1px solid #b9c9cf;border-radius:10px;background:#fff;font:16px inherit}.auth-card input:focus-visible,.auth-card button:focus-visible{outline:3px solid #8bc4d1;outline-offset:2px}.auth-card button{width:100%;min-height:46px;margin-top:16px;border:1px solid #123f55;border-radius:10px;background:#123f55;color:#fff;font:700 15px inherit;cursor:pointer}.auth-card button:hover{background:#0c3042}.auth-card button:disabled{opacity:.65;cursor:wait}.auth-error{min-height:20px;margin:12px 0 0;color:#9a302d;font-size:13px;line-height:1.5}.auth-loading{width:min(480px,100%);padding:36px;border:1px solid #dce5e8;border-radius:14px;background:#fff;box-shadow:0 7px 22px rgba(22,55,68,.07)}.auth-loading p{margin:0;color:#267084;font-size:12px;font-weight:800;letter-spacing:.1em}.auth-loading h1{margin:10px 0 0;color:#123f55;font-size:22px}@media(max-width:720px){.auth-shell{padding:16px}.auth-layout{grid-template-columns:1fr;gap:16px}.auth-intro{min-height:auto;padding:28px 24px}.auth-intro h1{font-size:28px}.auth-card{padding:26px 22px}}
</style>`;

function showLoading(message = '認証状態を確認しています…') { document.body.style.visibility = 'visible'; document.body.innerHTML = `${authStyle}<main class="auth-shell"><section class="auth-loading"><p>SECURE ACCESS</p><h1>${message}</h1></section></main>`; }
function showLogin(error = '') { document.body.style.visibility = 'visible'; document.body.innerHTML = `${authStyle}<main class="auth-shell"><div class="auth-layout"><section class="auth-intro"><p class="auth-eyebrow">CHILD EXPENSE SETTLEMENT</p><h1>証拠を見ながら、清算を確かに整理する。</h1><p>子どもに関する支出資料と清算額を、端末内の原本と紐づけて管理できます。</p><ul class="auth-points"><li>原本と明細を双方向に確認</li><li>OCR候補は人が確認してから登録</li><li>経費・原本はブラウザ内に保存</li></ul></section><section class="auth-card"><p class="auth-eyebrow">SECURE ACCESS</p><h1>ログイン</h1><p>管理者から発行された利用者アカウントでログインしてください。</p><form id="login"><label>メールアドレス</label><input name="email" type="email" autocomplete="email" required><label>パスワード</label><input name="password" type="password" autocomplete="current-password" required><p class="auth-error">${error}</p><button type="submit">ログイン</button></form></section></div></main>`; $('#login').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('button'); button.disabled = true; try { await auth.signIn(form.email.value, form.password.value); location.reload(); } catch (cause) { showLogin(cause.message || 'ログインに失敗しました。'); } }); }

export async function requireAuthenticatedUser() { showLoading(); if (!auth.configured) { showLogin('認証設定が未登録です。管理者へ連絡してください。'); return new Promise(() => {}); } try { const session = await auth.getSession(); if (session?.user) return session.user; showLogin(); return new Promise(() => {}); } catch (cause) { showLogin(cause.message || '認証状態を確認できませんでした。'); return new Promise(() => {}); } }
export async function logout() { await auth.signOut(); location.reload(); }
export async function getAccessToken() { return (await auth.getSession())?.access_token || null; }
