import { createAuthService } from './services/auth.js';

const config = globalThis.__APP_CONFIG__ || {};
export const auth = createAuthService({ url: config.supabaseUrl, anonKey: config.supabaseAnonKey });

function showLoading(message = '認証状態を確認しています…') { document.body.style.visibility = 'visible'; document.body.innerHTML = `<main class="auth-shell"><section><p>子ども関連支出 清算整理</p><h1>${message}</h1></section></main>`; }
function showLogin(error = '') { document.body.style.visibility = 'visible'; document.body.innerHTML = `<style>.auth-shell{min-height:100vh;display:grid;place-items:center;background:#eef3f5;font-family:system-ui,"Yu Gothic UI",sans-serif}.auth-shell section{width:min(380px,calc(100vw - 32px));padding:28px;background:#fff;border:1px solid #cedae0}.auth-shell h1{font-size:20px}.auth-shell label,.auth-shell input{display:block;width:100%;box-sizing:border-box}.auth-shell label{margin:14px 0 4px;font-weight:700}.auth-shell input{padding:9px;border:1px solid #9fb1ba}.auth-shell button{width:100%;margin-top:18px;padding:10px;background:#17455d;color:#fff;border:0}.auth-error{color:#9a302d;min-height:20px}</style><main class="auth-shell"><section><p>子ども関連支出 清算整理</p><h1>ログイン</h1><p>発行済みの利用者アカウントでログインしてください。</p><form id="login"><label>メールアドレス</label><input name="email" type="email" autocomplete="email" required><label>パスワード</label><input name="password" type="password" autocomplete="current-password" required><p class="auth-error">${error}</p><button type="submit">ログイン</button></form></section></main>`; $('#login').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('button'); button.disabled = true; try { await auth.signIn(form.email.value, form.password.value); location.reload(); } catch (cause) { showLogin(cause.message || 'ログインに失敗しました。'); } }); }
const $ = (selector) => document.querySelector(selector);

export async function requireAuthenticatedUser() { showLoading(); if (!auth.configured) { showLogin('認証設定が未登録です。管理者へ連絡してください。'); return new Promise(() => {}); } try { const session = await auth.getSession(); if (session?.user) return session.user; showLogin(); return new Promise(() => {}); } catch (cause) { showLogin(cause.message || '認証状態を確認できませんでした。'); return new Promise(() => {}); } }
export async function logout() { await auth.signOut(); location.reload(); }
