import { calculateSummary } from './calculations.js';

const field = (value) => value?.value ?? value ?? '';
const yen = (value) => Number(value || 0).toLocaleString('ja-JP');
const escapeCsv = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`;
export function makeCsv(records, evidenceById, childById) {
  const headers = ['証拠番号', '支払日', '支払先', '対象児童', '費目', '金額', '養育関連区分', '特別費区分', '支出理由', '自分負担率', '相手負担率', '相手負担額', '既払い額', '未清算額', '状態', '備考'];
  const rows = records.map((record) => [
    (record.evidenceIds || []).map((id) => evidenceById.get(id)?.evidenceNumber || '').join(' / '), record.paidDate, field(record.vendor), childById.get(field(record.childId))?.name || '', field(record.category), record.amount?.value ?? record.amount, field(record.parentingExpenseStatus), field(record.specialExpenseStatus), field(record.reason), record.selfBurdenRate, record.otherBurdenRate, record.otherBurdenAmount, record.alreadyPaidAmount, record.outstandingAmount, field(record.settlementStatus), record.notes,
  ]);
  return '\uFEFF' + [headers, ...rows].map((row) => row.map(escapeCsv).join(',')).join('\r\n');
}
export function downloadCsv(records, evidenceById, childById) { const blob = new Blob([makeCsv(records, evidenceById, childById)], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = Object.assign(document.createElement('a'), { href: url, download: `子ども関連支出_清算一覧_${new Date().toISOString().slice(0, 10)}.csv` }); a.click(); URL.revokeObjectURL(url); }
export function makePrintHtml(records, evidenceById, childById, periodLabel) {
  const summary = calculateSummary(records); const rows = records.map((r) => `<tr><td>${(r.evidenceIds || []).map((id) => evidenceById.get(id)?.evidenceNumber || '').join('<br>')}</td><td>${r.paidDate}</td><td>${childById.get(field(r.childId))?.name || ''}</td><td>${field(r.category)}</td><td>${field(r.vendor)}</td><td class="amount">¥${yen(r.amount?.value ?? r.amount)}</td><td class="amount">¥${yen(r.otherBurdenAmount)}</td><td class="amount">¥${yen(r.alreadyPaidAmount)}</td><td class="amount">¥${yen(r.outstandingAmount)}</td><td>${field(r.reason)}</td><td>${field(r.settlementStatus)}</td></tr>`).join('');
  return `<article class="print-sheet"><h1>子ども関連支出 清算一覧</h1><p>対象期間：${periodLabel}</p><section class="print-summary"><span>支出総額　¥${yen(summary.amount)}</span><span>相手負担想定額　¥${yen(summary.other)}</span><span>既払い額　¥${yen(summary.paid)}</span><span>未清算額　¥${yen(summary.outstanding)}</span></section><table><thead><tr><th>証拠番号</th><th>支払日</th><th>対象児童</th><th>費目</th><th>支払先</th><th>金額</th><th>相手負担</th><th>既払い</th><th>未清算</th><th>支出理由</th><th>状態</th></tr></thead><tbody>${rows || '<tr><td colspan="11">該当する明細がありません。</td></tr>'}</tbody></table></article>`;
}


export function makeReceiptSummaryCsv(records, evidenceById) { const headers = ['\u8a3c\u62e0\u756a\u53f7','\u8cfc\u5165\u65e5','\u8cfc\u5165\u5e97','\u30ec\u30b7\u30fc\u30c8\u7dcf\u984d','\u5546\u54c1\u660e\u7d30\u5408\u8a08','\u63d0\u51fa\u5bfe\u8c61\u984d','\u5dee\u984d']; const rows = (records || []).map((record) => [(record.evidenceIds || []).map((id) => evidenceById.get(id)?.evidenceNumber || '').join(' / '),record.paidDate,field(record.vendor),record.receiptTotalAmount ?? record.amount?.value ?? record.amount ?? 0,(record.items || []).reduce((sum,item) => sum + (Number(item.amount) || 0),0),(record.items || []).filter((item) => item.submissionStatus === 'included').reduce((sum,item) => sum + (Number(item.amount) || 0),0),(record.receiptTotalAmount ?? record.amount?.value ?? record.amount ?? 0) - (record.items || []).reduce((sum,item) => sum + (Number(item.amount) || 0),0)]); return '\uFEFF' + [headers,...rows].map((row) => row.map(escapeCsv).join(',')).join('\r\n'); }
export function makeReceiptItemsCsv(records, evidenceById) { const headers = ['\u8a3c\u62e0\u756a\u53f7','\u8cfc\u5165\u65e5','\u5e97\u540d','\u5546\u54c1\u540d','\u6570\u91cf','\u5358\u4fa1','\u91d1\u984d','\u7a2e\u5225','\u8cfc\u5165\u76ee\u7684\u30fb\u5fc5\u8981\u6027','\u63d0\u51fa\u72b6\u614b','\u6839\u62e0','\u5099\u8003']; const rows = (records || []).flatMap((record) => (record.items || []).map((item) => [(record.evidenceIds || []).map((id) => evidenceById.get(id)?.evidenceNumber || '').join(' / '),record.paidDate,field(record.vendor),item.productName,item.quantity,item.unitPrice,item.amount,item.category,field(item.purpose),item.submissionStatus,(item.basis || []).join(' / '),item.notes])); return '\uFEFF' + [headers,...rows].map((row) => row.map(escapeCsv).join(',')).join('\r\n'); }
export function downloadReceiptCsv(content, filename) { const blob = new Blob([content], { type:'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = Object.assign(document.createElement('a'), { href:url, download:filename }); anchor.click(); URL.revokeObjectURL(url); }
